INSERT INTO community (name, uc, regional, city_id) VALUES
	('Ebenezer (Maués)','FE Maués','Negro Amazonas','240'),
	('Liberdade (Maués)','FE Maués','Negro Amazonas','240'),
	('Menino Deus do Acãoera','FE Maués','Negro Amazonas','240'),
	('Monte Sinai do Rio Apoquitaua','FE Maués','Negro Amazonas','240'),
	('Monte Sinai do Rio Parauarí','FE Maués','Negro Amazonas','240'),
	('Nossa Senhora Aparecida do Rio Parauarí','FE Maués','Negro Amazonas','240'),
	('Nossa Senhora Aparecida Rio Apoquitaua','FE Maués','Negro Amazonas','240'),
	('Nova Jerusalém (Maués)','FE Maués','Negro Amazonas','240'),
	('Novo Paraíso/Jatuarana','FE Maués','Negro Amazonas','240'),
	('Santa Maria do Cincatá','FE Maués','Negro Amazonas','240'),
	('Santo Antônio do Mucajá','FE Maués','Negro Amazonas','240'),
	('Santo Antonio do Pucu','FE Maués','Negro Amazonas','240'),
	('São João Batista do Rio Apoquitaua (Pacoval)','FE Maués','Negro Amazonas','240'),
	('São João Batista do Rio Parauarí','FE Maués','Negro Amazonas','240'),
	('São José do Cincantá','FE Maués','Negro Amazonas','240'),
	('São Luiz do Laranjal','FE Maués','Negro Amazonas','240'),
	('São Raimundo (Maués)','FE Maués','Negro Amazonas','240'),
	('São Sebastião (Maués)','FE Maués','Negro Amazonas','240'),
	('Vila Darci','FE Maués','Negro Amazonas','240'),
	('Vila Nova Maringá','FE Maués','Negro Amazonas','240'),
	('Vista Alegre (Maués)','FE Maués','Negro Amazonas','240'),
	('Barra Mansa','RDS Canumã','Negro Amazonas','240'),
	('Cumatê','RDS Canumã','Negro Amazonas','240'),
	('Estrela do Oriente','RDS Canumã','Negro Amazonas','240'),
	('Foz Canumã','RDS Canumã','Negro Amazonas','240'),
	('Nova Aparecida','RDS Canumã','Negro Amazonas','240'),
	('Nova Vida','RDS Canumã','Negro Amazonas','240'),
	('Novo São João','RDS Canumã','Negro Amazonas','240'),
	('Pindobal 1','RDS Canumã','Negro Amazonas','240'),
	('Pindobal 2','RDS Canumã','Negro Amazonas','240'),
	('Samaria','RDS Canumã','Negro Amazonas','240'),
	('Santa Ana do Amanium','RDS Canumã','Negro Amazonas','240'),
	('Santa Rita','RDS Canumã','Negro Amazonas','240'),
	('Santo Antônio do Lira','RDS Canumã','Negro Amazonas','240'),
	('São José (Canumã)','RDS Canumã','Negro Amazonas','240'),
	('São José do Jerônimo','RDS Canumã','Negro Amazonas','240'),
	('São Raimundo do Rio Abacaxi','RDS Canumã','Negro Amazonas','240'),
	('Sítio São Raimundo','RDS Canumã','Negro Amazonas','240'),
	('Vila do Abacaxis','RDS Canumã','Negro Amazonas','240'),
	('Vila do Canumã','RDS Canumã','Negro Amazonas','240'),
	('Vista Alegre (Canumã)','RDS Canumã','Negro Amazonas','240'),
	('Bela Vista (Uatumã)','RDS do Uatumã','Negro Amazonas','240'),
	('Bom Jesus do Angelim (Uatumã)','RDS do Uatumã','Negro Amazonas','240'),
	('Cesaréia','RDS do Uatumã','Negro Amazonas','240'),
	('Deus Ajude do Boto','RDS do Uatumã','Negro Amazonas','240'),
	('Ebenezer das Pedras','RDS do Uatumã','Negro Amazonas','240'),
	('Emanuel/Serra do Jacamim','RDS do Uatumã','Negro Amazonas','240'),
	('Maanaim','RDS do Uatumã','Negro Amazonas','240'),
	('Monte das Oliveiras (Uatumã)','RDS do Uatumã','Negro Amazonas','240'),
	('Monte Sião do Leandro Grande','RDS do Uatumã','Negro Amazonas','240'),
	('Nossa Senhora Aparecida do Arara (Ararinha)','RDS do Uatumã','Negro Amazonas','240'),
	('Nossa Senhora Aparecida do Flechal (Uatumã)','RDS do Uatumã','Negro Amazonas','240'),
	('Nossa Senhora de Fátima do Caioé Grande','RDS do Uatumã','Negro Amazonas','240'),
	('Nossa Senhora do Livramento (Uatumã)','RDS do Uatumã','Negro Amazonas','240'),
	('Nossa Senhora do Perpetuo Socorro Maracarana','RDS do Uatumã','Negro Amazonas','240'),
	('Nova Jerusalém do Amaro','RDS do Uatumã','Negro Amazonas','240'),
	('Santa Helena do Abacate','RDS do Uatumã','Negro Amazonas','240'),
	('Santa Luzia Caranatuba','RDS do Uatumã','Negro Amazonas','240'),
	('Santa Luzia de Jacarequara','RDS do Uatumã','Negro Amazonas','240'),
	('São Benedito','RDS do Uatumã','Negro Amazonas','240'),
	('São Francisco do Caribi','RDS do Uatumã','Negro Amazonas','240'),
	('Costa do Ubim','APA do Rio Negro','Negro Amazonas','240'),
	('Maravilha','APA do Rio Negro','Negro Amazonas','240'),
	('Monte Sinai do Igarapé Açú','APA do Rio Negro','Negro Amazonas','240'),
	('Nova Aliança','APA do Rio Negro','Negro Amazonas','240'),
	('Nova Canaã do Aruaú','APA do Rio Negro','Negro Amazonas','240'),
	('Nova Jerusalém','APA do Rio Negro','Negro Amazonas','240'),
	('Santa Isabel','APA do Rio Negro','Negro Amazonas','240'),
	('São Sebastião Cueiras','APA do Rio Negro','Negro Amazonas','240'),
	('São Tomé (Indigena)','APA do Rio Negro','Negro Amazonas','240'),
	('Três Unidos (Aldeia)','APA do Rio Negro','Negro Amazonas','240'),
	('Arara','RDS Puranga Conquista','Negro Amazonas','240'),
	('Baixote','RDS Puranga Conquista','Negro Amazonas','240'),
	('Barreirinha','RDS Puranga Conquista','Negro Amazonas','240'),
	('Bela Vista Jaraqui','RDS Puranga Conquista','Negro Amazonas','240'),
	('Caioé','RDS Puranga Conquista','Negro Amazonas','240'),
	('Nova Canaã (rio cuieiras)','RDS Puranga Conquista','Negro Amazonas','240'),
	('Nova Esperança do Cueiras','RDS Puranga Conquista','Negro Amazonas','240'),
	('Pagodão','RDS Puranga Conquista','Negro Amazonas','240'),
	('Santa Maria','RDS Puranga Conquista','Negro Amazonas','240'),
	('São Francisco do Solimõezinho','RDS Puranga Conquista','Negro Amazonas','240'),
	('Terra Preta','RDS Puranga Conquista','Negro Amazonas','240'),
	('Vila Nova do Chita (São Francisco do Chita)','RDS Puranga Conquista','Negro Amazonas','240'),
	('15 de Setembro','RDS do Rio Negro','Negro Amazonas','240'),
	('Camará','RDS do Rio Negro','Negro Amazonas','240'),
	('Carão','RDS do Rio Negro','Negro Amazonas','240'),
	('Marajá','RDS do Rio Negro','Negro Amazonas','240'),
	('Nossa Senhora da Conceição','RDS do Rio Negro','Negro Amazonas','240'),
	('Nossa Senhora de Fátima (Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Nossa Senhora Perpétuo Socorro (Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Nova Aliança','RDS do Rio Negro','Negro Amazonas','240'),
	('Nova Esperança (Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Santa Helena do Inglês(Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Santo Antônio (Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Santo Antônio do Lago do Tiririca','RDS do Rio Negro','Negro Amazonas','240'),
	('São Francisco do Bujaru','RDS do Rio Negro','Negro Amazonas','240'),
	('São Tomé (Rio Negro)','RDS do Rio Negro','Negro Amazonas','240'),
	('Saracá','RDS do Rio Negro','Negro Amazonas','240'),
	('Terra Preta','RDS do Rio Negro','Negro Amazonas','240'),
	('Terra Santa','RDS do Rio Negro','Negro Amazonas','240'),
	('Tiririca','RDS do Rio Negro','Negro Amazonas','240'),
	('Tumbiras','RDS do Rio Negro','Negro Amazonas','240'),
	('Arapapá/Arpouba','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Beabá de Baixo','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Beabá de Cima','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Boa Esperança (boca do evaristo)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Boa Morada','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Boas Novas','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Boca do Campina','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Bom Jesus (Piagaçú)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Campina','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Capoeirinha','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Caua (Localidade )','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Costa do carapanã','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Costa do Paricatuba','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Cuiuanã','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Deus é Amor','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Divino Espirito Santo (Pinheiros)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Evaristo','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Fortaleza','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Frangolhão','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Guajaratuba','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Itaboca','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Itapuru','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Jericó','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Lago do Arumã','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Laranjal','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Linda Conceição','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Monte das Oliveiras (Piagaçu)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora Aparecida','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora da Conceição/Santa Rosa','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora de Fátima do Rosário','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora de Nazaré (Piagaçú)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora do Livramento (Uixi)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Senhora do Perpétuo Socorro (Tuiué)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nossa Sra. do Carmo (Lago do Ipiranga)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nova Esperança I (Piagaçu)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nova Jerusalem (Piagaçu)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Nova Morada','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Novo Juruti','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Novo Supiá','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Redenção','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Santa Filomena','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Santa Luzia Lago do Jari (Piagaçú)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Santa Rita (Piagaçú)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Santana do Supiá','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Francisco (Piagaçu)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Francisco das 3 Bocas','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Francisco do Bacuri','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Francisco do Marrecão','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São João Batista (Piagaçu)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São João Batista do Lago do Uauaçu','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São João das 3 Bocas','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Jose do Supia','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Lázaro','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Pedro','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Raimundo (Aimim)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('São Sebastião (Piagaçú)','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Surara','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Tambaqui','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Ubim','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Vila Araujo','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Vila do Paricatuba','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Vila Miranda','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Vista do Ipiranga','RDS Piagaçu-Purus','Negro Amazonas','240'),
	('Açaituba (Amanã)','RDS Amanã','Solimões','240'),
	('Belo Monte (Amanã)','RDS Amanã','Solimões','240'),
	('Betel','RDS Amanã','Solimões','240'),
	('Boa Esperança do Amanã','RDS Amanã','Solimões','240'),
	('Boa Fé do Joacaca','RDS Amanã','Solimões','240'),
	('Boa Vista do Calafate','RDS Amanã','Solimões','240'),
	('Bom Jesus do Baré','RDS Amanã','Solimões','240'),
	('Bom Jesus do Lago Preto (Amanã)','RDS Amanã','Solimões','240'),
	('Bom Socorro','RDS Amanã','Solimões','240'),
	('Bom Sucesso (Amanã)','RDS Amanã','Solimões','240'),
	('Carburini','RDS Amanã','Solimões','240'),
	('Comapara','RDS Amanã','Solimões','240'),
	('Comunidade Do Piranha','RDS Amanã','Solimões','240'),
	('Curupira (Usuário)','RDS Amanã','Solimões','240'),
	('Ebenezer (Amanã)','RDS Amanã','Solimões','240'),
	('Iracema','RDS Amanã','Solimões','240'),
	('Japão','RDS Amanã','Solimões','240'),
	('Lago do Caruara','RDS Amanã','Solimões','240'),
	('Matuzalém','RDS Amanã','Solimões','240'),
	('Monte Alegre','RDS Amanã','Solimões','240'),
	('Monte Ararate','RDS Amanã','Solimões','240'),
	('Monte Carmelo','RDS Amanã','Solimões','240'),
	('Monte Sião (Amanã)','RDS Amanã','Solimões','240'),
	('Monte Sinai (Amanã)','RDS Amanã','Solimões','240'),
	('Nossa Senhora de Fátima (Amanã)','RDS Amanã','Solimões','240'),
	('Nova Betânia (Maraã)','RDS Amanã','Solimões','240'),
	('Nova Canaã','RDS Amanã','Solimões','240'),
	('Nova Esperança','RDS Amanã','Solimões','240'),
	('Nova Esperança do Abico','RDS Amanã','Solimões','240'),
	('Nova Esperança do Joacaca (Amanã)','RDS Amanã','Solimões','240'),
	('Nova Esperança do Urumutum','RDS Amanã','Solimões','240'),
	('Nova Jacitara','RDS Amanã','Solimões','240'),
	('Nova Jerusalém (Amanã)','RDS Amanã','Solimões','240'),
	('Nova Macedônia','RDS Amanã','Solimões','240'),
	('Nova Olinda (Amanã)','RDS Amanã','Solimões','240'),
	('Nova Samaria','RDS Amanã','Solimões','240'),
	('Nova Tapira (Amanã)','RDS Amanã','Solimões','240'),
	('Novo Joacaca (Amanã)','RDS Amanã','Solimões','240'),
	('Novo Pirapucu (Amanã)','RDS Amanã','Solimões','240'),
	('Paraíso (Amanã)','RDS Amanã','Solimões','240'),
	('Porto Alegre (Amanã)','RDS Amanã','Solimões','240'),
	('Porto Alves (Amanã)','RDS Amanã','Solimões','240'),
	('Santa Isabel','RDS Amanã','Solimões','240'),
	('Santa Luzia do Baré','RDS Amanã','Solimões','240'),
	('Santa Luzia do Juazinho','RDS Amanã','Solimões','240'),
	('Santa Maria do Cururu','RDS Amanã','Solimões','240'),
	('Santo Antônio do Paraná do Caixão','RDS Amanã','Solimões','240'),
	('Santo Estevão','RDS Amanã','Solimões','240'),
	('São Francisco da Boca do Cubuá','RDS Amanã','Solimões','240'),
	('São Francisco do Cururu','RDS Amanã','Solimões','240'),
	('São João do Ipecaçu','RDS Amanã','Solimões','240'),
	('São José do Mercejana','RDS Amanã','Solimões','240'),
	('São José do Urini','RDS Amanã','Solimões','240'),
	('São Paulo (Amanã)','RDS Amanã','Solimões','240'),
	('São Pedro (Amanã)','RDS Amanã','Solimões','240'),
	('São Sebastião Do Repartimento(Coraci)','RDS Amanã','Solimões','240'),
	('Ubim (Amanã)','RDS Amanã','Solimões','240'),
	('Varzéa Alegre','RDS Amanã','Solimões','240'),
	('Vila Nova do Coracy','RDS Amanã','Solimões','240'),
	('Vila Nova do Paraná do Amanã','RDS Amanã','Solimões','240'),
	('Vila Nova do Putiri (Amanã)','RDS Amanã','Solimões','240'),
	('Vista Alegre (Amanã)','RDS Amanã','Solimões','240'),
	('Acapuri de Baixo','RDS Mamirauá','Solimões','240'),
	('Acapuri de Cima','RDS Mamirauá','Solimões','240'),
	('Acapuri do meio','RDS Mamirauá','Solimões','240'),
	('Acari','RDS Mamirauá','Solimões','240'),
	('Agua Branca','RDS Mamirauá','Solimões','240'),
	('Araçarí (Localidade)','RDS Mamirauá','Solimões','240'),
	('Arauaça','RDS Mamirauá','Solimões','240'),
	('Arutá','RDS Mamirauá','Solimões','240'),
	('Assunção','RDS Mamirauá','Solimões','240'),
	('Baixo das Araras','RDS Mamirauá','Solimões','240'),
	('Bananal (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Barão da Saudade','RDS Mamirauá','Solimões','240'),
	('Barreirinha de Cima','RDS Mamirauá','Solimões','240'),
	('Barreirinha do Peixe (localidade)','RDS Mamirauá','Solimões','240'),
	('Barrerinha de Baixo','RDS Mamirauá','Solimões','240'),
	('Barroso','RDS Mamirauá','Solimões','240'),
	('Batalha de Baixo','RDS Mamirauá','Solimões','240'),
	('Bate Papo','RDS Mamirauá','Solimões','240'),
	('Bela Vista do Batalha','RDS Mamirauá','Solimões','240'),
	('Boa Sorte','RDS Mamirauá','Solimões','240'),
	('Boa União','RDS Mamirauá','Solimões','240'),
	('Boa Vista (Setor Barroso)','RDS Mamirauá','Solimões','240'),
	('Boa Vista da Campina','RDS Mamirauá','Solimões','240'),
	('Boa Vista do Capote','RDS Mamirauá','Solimões','240'),
	('Boa Vista do Pema','RDS Mamirauá','Solimões','240'),
	('Boa Vista do Viola','RDS Mamirauá','Solimões','240'),
	('Boca do Auati-Paraná/Paraná de Baixo','RDS Mamirauá','Solimões','240'),
	('Boca do Guariba (Mamirauá)-(Localidade)','RDS Mamirauá','Solimões','240'),
	('Boca do Guedes','RDS Mamirauá','Solimões','240'),
	('Boca do Inambé','RDS Mamirauá','Solimões','240'),
	('Boca do Julio','RDS Mamirauá','Solimões','240'),
	('Boca do Jurupari','RDS Mamirauá','Solimões','240'),
	('Boca do Mamirauá','RDS Mamirauá','Solimões','240'),
	('Boca do Pema','RDS Mamirauá','Solimões','240'),
	('Boca do Prata','RDS Mamirauá','Solimões','240'),
	('Boca do Tigre','RDS Mamirauá','Solimões','240'),
	('Boca do Tupé','RDS Mamirauá','Solimões','240'),
	('Boiador','RDS Mamirauá','Solimões','240'),
	('Boiaquara','RDS Mamirauá','Solimões','240'),
	('Bom Jardim','RDS Mamirauá','Solimões','240'),
	('Bom Jesus do Solimões','RDS Mamirauá','Solimões','240'),
	('Bom Sucesso','RDS Mamirauá','Solimões','240'),
	('Breu','RDS Mamirauá','Solimões','240'),
	('Bugari/Urutubinha','RDS Mamirauá','Solimões','240'),
	('Camador','RDS Mamirauá','Solimões','240'),
	('Campo Novo','RDS Mamirauá','Solimões','240'),
	('Canaria','RDS Mamirauá','Solimões','240'),
	('Capote','RDS Mamirauá','Solimões','240'),
	('Caridade','RDS Mamirauá','Solimões','240'),
	('Castelo','RDS Mamirauá','Solimões','240'),
	('Catite (Localidade)','RDS Mamirauá','Solimões','240'),
	('Coadi','RDS Mamirauá','Solimões','240'),
	('Comunidade do Machado','RDS Mamirauá','Solimões','240'),
	('Cordeiro','RDS Mamirauá','Solimões','240'),
	('Costa da Capoeira','RDS Mamirauá','Solimões','240'),
	('Costa da Ilha II','RDS Mamirauá','Solimões','240'),
	('Cruzeiro','RDS Mamirauá','Solimões','240'),
	('Cuiaba','RDS Mamirauá','Solimões','240'),
	('Curimata de baixo','RDS Mamirauá','Solimões','240'),
	('Curimata de Cima','RDS Mamirauá','Solimões','240'),
	('Deus é Pai','RDS Mamirauá','Solimões','240'),
	('Estirão do Itaúba','RDS Mamirauá','Solimões','240'),
	('Fazenda Nova','RDS Mamirauá','Solimões','240'),
	('Floresta','RDS Mamirauá','Solimões','240'),
	('Fonte da Luz','RDS Mamirauá','Solimões','240'),
	('Furo','RDS Mamirauá','Solimões','240'),
	('Gloria','RDS Mamirauá','Solimões','240'),
	('Ilha do Chibeco','RDS Mamirauá','Solimões','240'),
	('Ingá','RDS Mamirauá','Solimões','240'),
	('Ingaioara','RDS Mamirauá','Solimões','240'),
	('Itaboca (Localidade)','RDS Mamirauá','Solimões','240'),
	('Jenipapo de Fora','RDS Mamirauá','Solimões','240'),
	('Jerusalém','RDS Mamirauá','Solimões','240'),
	('Juruamã','RDS Mamirauá','Solimões','240'),
	('Localidade Juliana (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Luís','RDS Mamirauá','Solimões','240'),
	('Maguarí/Aranapu','RDS Mamirauá','Solimões','240'),
	('Manacabi','RDS Mamirauá','Solimões','240'),
	('Mapurilândia','RDS Mamirauá','Solimões','240'),
	('Maratá','RDS Mamirauá','Solimões','240'),
	('Mari Mari','RDS Mamirauá','Solimões','240'),
	('Marirana','RDS Mamirauá','Solimões','240'),
	('Miriti','RDS Mamirauá','Solimões','240'),
	('Monte Cristo','RDS Mamirauá','Solimões','240'),
	('Monte das Oliveiras (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Monte Horebe','RDS Mamirauá','Solimões','240'),
	('Monte Moriá','RDS Mamirauá','Solimões','240'),
	('Monte Sião','RDS Mamirauá','Solimões','240'),
	('Mororo','RDS Mamirauá','Solimões','240'),
	('Moura','RDS Mamirauá','Solimões','240'),
	('Mulatinho','RDS Mamirauá','Solimões','240'),
	('Murinzal','RDS Mamirauá','Solimões','240'),
	('Nossa Senhora da Saúde','RDS Mamirauá','Solimões','240'),
	('Nossa Senhora de Fátima (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Nossa Sra. Aparecida (Localidade Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Nova Colômbia','RDS Mamirauá','Solimões','240'),
	('Nova Esperança (Mamuriá)','RDS Mamirauá','Solimões','240'),
	('Nova Esperança de Baixo','RDS Mamirauá','Solimões','240'),
	('Nova Esperança do Cruzeiro','RDS Mamirauá','Solimões','240'),
	('Nova Esperança do Jenipapo','RDS Mamirauá','Solimões','240'),
	('Nova Jerusalem do Aranapu','RDS Mamirauá','Solimões','240'),
	('Nova Jerusalém do Maiana','RDS Mamirauá','Solimões','240'),
	('Nova Macedônia (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Novo Hamburgo','RDS Mamirauá','Solimões','240'),
	('Novo Horizonte','RDS Mamirauá','Solimões','240'),
	('Novo Viola','RDS Mamirauá','Solimões','240'),
	('Pacu','RDS Mamirauá','Solimões','240'),
	('Pãozal','RDS Mamirauá','Solimões','240'),
	('Paraíso do Macopani','RDS Mamirauá','Solimões','240'),
	('Paraná do Catipuru (Localidade)','RDS Mamirauá','Solimões','240'),
	('Paraná do Tupé','RDS Mamirauá','Solimões','240'),
	('Pentecostal','RDS Mamirauá','Solimões','240'),
	('Petrolina','RDS Mamirauá','Solimões','240'),
	('Pinheiro de Cima','RDS Mamirauá','Solimões','240'),
	('Pinheiro do Meio','RDS Mamirauá','Solimões','240'),
	('Pirarara de Baixo','RDS Mamirauá','Solimões','240'),
	('Ponto X','RDS Mamirauá','Solimões','240'),
	('Porto Alegre (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Porto Braga','RDS Mamirauá','Solimões','240'),
	('Porto Inhuma','RDS Mamirauá','Solimões','240'),
	('Porto Nazaré','RDS Mamirauá','Solimões','240'),
	('Porto Novo','RDS Mamirauá','Solimões','240'),
	('Porto Pirum','RDS Mamirauá','Solimões','240'),
	('Porto Praia','RDS Mamirauá','Solimões','240'),
	('Porto São Francisco','RDS Mamirauá','Solimões','240'),
	('Porto Seguro','RDS Mamirauá','Solimões','240'),
	('Punã','RDS Mamirauá','Solimões','240'),
	('Remanso/Mamirauá','RDS Mamirauá','Solimões','240'),
	('Reserva do Mulato','RDS Mamirauá','Solimões','240'),
	('Samaumeira (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Santa Domicia','RDS Mamirauá','Solimões','240'),
	('Santa Fé (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Santa Luzia (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Santa Luzia do Jussara','RDS Mamirauá','Solimões','240'),
	('Santa Maria (Mamairauá)','RDS Mamirauá','Solimões','240'),
	('Santa Tereza','RDS Mamirauá','Solimões','240'),
	('Santa União','RDS Mamirauá','Solimões','240'),
	('São Caetano','RDS Mamirauá','Solimões','240'),
	('São Cristovão','RDS Mamirauá','Solimões','240'),
	('São Francisco (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('São Francisco Chibecó do Meio','RDS Mamirauá','Solimões','240'),
	('São Francisco da Mangueira','RDS Mamirauá','Solimões','240'),
	('São Francisco do Aiuca','RDS Mamirauá','Solimões','240'),
	('São Francisco do Bóia','RDS Mamirauá','Solimões','240'),
	('São Francisco do Tucuxi','RDS Mamirauá','Solimões','240'),
	('São Francisco dos Piranhas','RDS Mamirauá','Solimões','240'),
	('São João (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('São João do Mineiro','RDS Mamirauá','Solimões','240'),
	('São José do Amparo','RDS Mamirauá','Solimões','240'),
	('São José do Batalha','RDS Mamirauá','Solimões','240'),
	('São José do Cuiu Cuiú','RDS Mamirauá','Solimões','240'),
	('São José do Jenipapo','RDS Mamirauá','Solimões','240'),
	('São José do Maiana','RDS Mamirauá','Solimões','240'),
	('São José do Mamirauá','RDS Mamirauá','Solimões','240'),
	('São Luiz Auati Paraná de Cima','RDS Mamirauá','Solimões','240'),
	('São Miguel','RDS Mamirauá','Solimões','240'),
	('São Raimundo do Batalha','RDS Mamirauá','Solimões','240'),
	('São Raimundo do Jarauá','RDS Mamirauá','Solimões','240'),
	('São Raimundo Panauã','RDS Mamirauá','Solimões','240'),
	('São Sebastião (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('São Sebastião do Batalha','RDS Mamirauá','Solimões','240'),
	('São Sebastião do Maiana','RDS Mamirauá','Solimões','240'),
	('Siria','RDS Mamirauá','Solimões','240'),
	('Sítio','RDS Mamirauá','Solimões','240'),
	('Sítio Boa Esperança','RDS Mamirauá','Solimões','240'),
	('Sítio Fortaleza','RDS Mamirauá','Solimões','240'),
	('Sítio Matero','RDS Mamirauá','Solimões','240'),
	('Sítio Promessa','RDS Mamirauá','Solimões','240'),
	('Sítio São Francisco do Pirarara','RDS Mamirauá','Solimões','240'),
	('Tabuleiro do Ferro','RDS Mamirauá','Solimões','240'),
	('Tacanal','RDS Mamirauá','Solimões','240'),
	('Tapira','RDS Mamirauá','Solimões','240'),
	('Terra Nova','RDS Mamirauá','Solimões','240'),
	('Triunfo','RDS Mamirauá','Solimões','240'),
	('Tupé','RDS Mamirauá','Solimões','240'),
	('Tupé do Meio','RDS Mamirauá','Solimões','240'),
	('Tururia','RDS Mamirauá','Solimões','240'),
	('União do Amazonas','RDS Mamirauá','Solimões','240'),
	('Vale da Benção','RDS Mamirauá','Solimões','240'),
	('Vencedor (Mamirauá)','RDS Mamirauá','Solimões','240'),
	('Vila Alencar','RDS Mamirauá','Solimões','240'),
	('Vila Alfaia','RDS Mamirauá','Solimões','240'),
	('Vila Soares','RDS Mamirauá','Solimões','240'),
	('Viola','RDS Mamirauá','Solimões','240'),
	('Volta do Apará Grande','RDS Mamirauá','Solimões','240'),
	('Bela Conquista','Resex Catuá-Ipixuna','Solimões','240'),
	('Divino Espirito Santo Catuá','Resex Catuá-Ipixuna','Solimões','240'),
	('Nossa Senhora de Fátima ( Indígena)','Resex Catuá-Ipixuna','Solimões','240'),
	('Nossa Senhora de Nazaré','Resex Catuá-Ipixuna','Solimões','240'),
	('Nossa Sra. Aparecida (Catuá)','Resex Catuá-Ipixuna','Solimões','240'),
	('Santa Fé (Catuá)','Resex Catuá-Ipixuna','Solimões','240'),
	('Santa Luzia do Bóia','Resex Catuá-Ipixuna','Solimões','240'),
	('Santa Sofia','Resex Catuá-Ipixuna','Solimões','240'),
	('São João do Catuá','Resex Catuá-Ipixuna','Solimões','240'),
	('São João Evangelista','Resex Catuá-Ipixuna','Solimões','240'),
	('São José do Catuá','Resex Catuá-Ipixuna','Solimões','240'),
	('São Lazáro (Catuá)','Resex Catuá-Ipixuna','Solimões','240'),
	('São Sebastião do Água Branca','Resex Catuá-Ipixuna','Solimões','240'),
	('Abelha','RDS do Juma','Madeira','240'),
	('Alvorada','RDS do Juma','Madeira','240'),
	('Amapá (Localidade)','RDS do Juma','Madeira','240'),
	('Amapazinho (Localidade)','RDS do Juma','Madeira','240'),
	('Amorim','RDS do Juma','Madeira','240'),
	('Barraquinha (Juma) localidade','RDS do Juma','Madeira','240'),
	('Belas Aguas','RDS do Juma','Madeira','240'),
	('Boa Frente','RDS do Juma','Madeira','240'),
	('Boa Vista (Juma)','RDS do Juma','Madeira','240'),
	('Boas Novas','RDS do Juma','Madeira','240'),
	('Cacaia','RDS do Juma','Madeira','240'),
	('Cipotuba','RDS do Juma','Madeira','240'),
	('Cristo Rei','RDS do Juma','Madeira','240'),
	('Cumã','RDS do Juma','Madeira','240'),
	('Flexal (Juma)','RDS do Juma','Madeira','240'),
	('Limão','RDS do Juma','Madeira','240'),
	('Livramento (Juma)','RDS do Juma','Madeira','240'),
	('Nova Jerusalem (Juma)','RDS do Juma','Madeira','240'),
	('Nova Olinda','RDS do Juma','Madeira','240'),
	('Nova Vida (Boca do Flexal)','RDS do Juma','Madeira','240'),
	('Novo Oriente (Juma)','RDS do Juma','Madeira','240'),
	('Paiucaua','RDS do Juma','Madeira','240'),
	('Primavera (Sivirino)','RDS do Juma','Madeira','240'),
	('Primor','RDS do Juma','Madeira','240'),
	('Repartimento','RDS do Juma','Madeira','240'),
	('Santa Maria (Juma)','RDS do Juma','Madeira','240'),
	('Santana do Arauazinho','RDS do Juma','Madeira','240'),
	('Santo Antônio do Taciua','RDS do Juma','Madeira','240'),
	('Santo Antônio Marepaua','RDS do Juma','Madeira','240'),
	('Santo Antônio-Capim-Tuba','RDS do Juma','Madeira','240'),
	('São Domingos (Localidade)','RDS do Juma','Madeira','240'),
	('São Felix','RDS do Juma','Madeira','240'),
	('São Francisco do Anape I','RDS do Juma','Madeira','240'),
	('São Francisco do Anape II','RDS do Juma','Madeira','240'),
	('São Francisco do Arauá','RDS do Juma','Madeira','240'),
	('São José dos Brazões','RDS do Juma','Madeira','240'),
	('São Marcos','RDS do Juma','Madeira','240'),
	('São Miguel da Boca do Juma','RDS do Juma','Madeira','240'),
	('Tucunaré','RDS do Juma','Madeira','240'),
	('Água Azul','RDS do Rio Amapá','Madeira','240'),
	('Boa Esperança (Rio Amapá)','RDS do Rio Amapá','Madeira','240'),
	('Democracia','RDS do Rio Amapá','Madeira','240'),
	('Jatuarana (Rio Amapá)','RDS do Rio Amapá','Madeira','240'),
	('Pandegal','RDS do Rio Amapá','Madeira','240'),
	('Santa Eva','RDS do Rio Amapá','Madeira','240'),
	('Santa Maria (Rio Amapá)','RDS do Rio Amapá','Madeira','240'),
	('Terra Preta/Terra indígena','RDS do Rio Amapá','Madeira','240'),
	('Urucury','RDS do Rio Amapá','Madeira','240'),
	('Vista Alegre (Rio Amapá)','RDS do Rio Amapá','Madeira','240'),
	('Alegria','RDS do Rio Madeira','Madeira','240'),
	('Amparo','RDS do Rio Madeira','Madeira','240'),
	('Bela Vista (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Bom Jesus (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Bom Sossego','RDS do Rio Madeira','Madeira','240'),
	('Bracinho','RDS do Rio Madeira','Madeira','240'),
	('Braço Grande','RDS do Rio Madeira','Madeira','240'),
	('Cachoeirinha','RDS do Rio Madeira','Madeira','240'),
	('Canadá','RDS do Rio Madeira','Madeira','240'),
	('Carapanaúba','RDS do Rio Madeira','Madeira','240'),
	('Cruzeiro','RDS do Rio Madeira','Madeira','240'),
	('Curupati','RDS do Rio Madeira','Madeira','240'),
	('Delícia','RDS do Rio Madeira','Madeira','240'),
	('Lago do Castanha','RDS do Rio Madeira','Madeira','240'),
	('Lago do São Luiz','RDS do Rio Madeira','Madeira','240'),
	('Livramento (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Mata-Mata','RDS do Rio Madeira','Madeira','240'),
	('Nossa Senhora de Nazaré (Madeira) - localidade','RDS do Rio Madeira','Madeira','240'),
	('Nova Estrela','RDS do Rio Madeira','Madeira','240'),
	('Nova Morada','RDS do Rio Madeira','Madeira','240'),
	('Novo Mundo (localidade)','RDS do Rio Madeira','Madeira','240'),
	('Novos Prazeres','RDS do Rio Madeira','Madeira','240'),
	('Prainha','RDS do Rio Madeira','Madeira','240'),
	('Quariuba (localidade)','RDS do Rio Madeira','Madeira','240'),
	('Realeza','RDS do Rio Madeira','Madeira','240'),
	('Realeza II','RDS do Rio Madeira','Madeira','240'),
	('Repartimento I','RDS do Rio Madeira','Madeira','240'),
	('Repartimento II','RDS do Rio Madeira','Madeira','240'),
	('Rio Preto (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Santa Maria (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Santa Rita (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Santa Rosa (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Santa Rosa II','RDS do Rio Madeira','Madeira','240'),
	('São Carlos','RDS do Rio Madeira','Madeira','240'),
	('São Francisco do Matupá','RDS do Rio Madeira','Madeira','240'),
	('São Francisco do Xiadá','RDS do Rio Madeira','Madeira','240'),
	('São João (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('São José (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('São Marajó','RDS do Rio Madeira','Madeira','240'),
	('São Pedro (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('São Sebastião Boca do Taciua','RDS do Rio Madeira','Madeira','240'),
	('São Sebastião do Lago Preto','RDS do Rio Madeira','Madeira','240'),
	('Sempre Viva','RDS do Rio Madeira','Madeira','240'),
	('Taciua','RDS do Rio Madeira','Madeira','240'),
	('Taperebá','RDS do Rio Madeira','Madeira','240'),
	('Uruá Brazão','RDS do Rio Madeira','Madeira','240'),
	('Vencedor (Madeira)','RDS do Rio Madeira','Madeira','240'),
	('Vencedorzinho','RDS do Rio Madeira','Madeira','240'),
	('Verdum','RDS do Rio Madeira','Madeira','240'),
	('Zé João','RDS do Rio Madeira','Madeira','240'),
	('São Francisco do Paraíso','RDS Cujubim','Juruá-Jutaí','240'),
	('Vila Cujubim','RDS Cujubim','Juruá-Jutaí','240'),
	('Barreira do Idó','RDS de Uacari','Juruá-Jutaí','240'),
	('Bauana','RDS de Uacari','Juruá-Jutaí','240'),
	('Belo Monte (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Boa Vista (Uacarí)','RDS de Uacari','Juruá-Jutaí','240'),
	('Boca do Xeruã','RDS de Uacari','Juruá-Jutaí','240'),
	('Bom Jesus (Uacarí)','RDS de Uacari','Juruá-Jutaí','240'),
	('Bonfim (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Cachoeira','RDS de Uacari','Juruá-Jutaí','240'),
	('Canta Galo','RDS de Uacari','Juruá-Jutaí','240'),
	('Caroçal','RDS de Uacari','Juruá-Jutaí','240'),
	('Idó','RDS de Uacari','Juruá-Jutaí','240'),
	('Mandioca - Vila Medeiros','RDS de Uacari','Juruá-Jutaí','240'),
	('Maracajá','RDS de Uacari','Juruá-Jutaí','240'),
	('Monte Carmelo','RDS de Uacari','Juruá-Jutaí','240'),
	('Monte Douro (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Morro Alto','RDS de Uacari','Juruá-Jutaí','240'),
	('Ouro Preto','RDS de Uacari','Juruá-Jutaí','240'),
	('Paraíso-Uacarí (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Porto Sade (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Pupunha','RDS de Uacari','Juruá-Jutaí','240'),
	('Remanso (Uacarí)','RDS de Uacari','Juruá-Jutaí','240'),
	('Samaumeira-Uacarí (Localidade)','RDS de Uacari','Juruá-Jutaí','240'),
	('Santo Antônio de Brito','RDS de Uacari','Juruá-Jutaí','240'),
	('São Francisco (Uacarí)','RDS de Uacari','Juruá-Jutaí','240'),
	('São José/Anaxiqui','RDS de Uacari','Juruá-Jutaí','240'),
	('Sororoca','RDS de Uacari','Juruá-Jutaí','240'),
	('Toari','RDS de Uacari','Juruá-Jutaí','240'),
	('Vila Ramalho','RDS de Uacari','Juruá-Jutaí','240'),
	('Xibauá','RDS de Uacari','Juruá-Jutaí','240'),
	('Xibauazinho','RDS de Uacari','Juruá-Jutaí','240'),
	('Atalaia (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Bacuri','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Boa Vista (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Charcão (localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Coatá (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Dalva (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Estirão (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Extrema (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Floresta (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Fortaleza (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Futuro','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Igarapé Preto','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Lago Grande','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Liberdade (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Localidade Lorena','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Maciel (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Maravilha','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Monte Alegre (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Muchila','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Morada Nova','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Prainha (localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Primeiro de Junho','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Recreio (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Santo Amaro (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('São João (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('São José (Localidade)','Resex do Rio Gregório','Juruá-Jutaí','240'),
	('Ubim (Gregório)','Resex do Rio Gregório','Juruá-Jutaí','240')
ON CONFLICT DO NOTHING;

INSERT INTO pages (title_url, url_path)
VALUES
	('Lista de Capítulos', 'capitulos'),
	('Registro de Capítulos', 'capitulos/dashboard'),
	('Lista de Usuários', 'usuarios'),
	('Registro de Usuários', 'usuarios/registro'),
	('Detalhes do Usuário', 'usuarios/detalhes'),
	('Informaçoes do Agente', 'agente-dashboard'),
	('Registro do Agente', 'agente-dashboard/registro'),
	('Detalhes do Agente', 'agente-dashboard/detalhes'),
	('Localização do Agente', 'agente-dashboard/localizacao'),
	('Histórico de Visita', 'agente-visita'),
	('Lista de Visitas', 'agente-visita/historico'),
	('Desempenho do Agente', 'agente-desempenho'),
	('Mapa dos Agentes', 'agentes-mapa'),
	('Lista de Perfis', 'perfis'),
	('Lista de Responsáveis', 'responsaveis'),
	('Detalhes do Responsável', 'responsaveis/detalhes'),
	('Registro do Responsável', 'responsaveis/registro'),
	('Lista de Gestantes', 'gestantes'),
	('Detalhes da Gestante', 'gestantes/detalhes'),
	('Registro da Gestante', 'gestantes/registro'),
	('Lista de Crianças', 'criancas'),
	('Detalhes da Criança', 'criancas/detalhes'),
	('Registro da Criança', 'criancas/registro'),
	('Lista de Comunidades', 'comunidades'),
	('Registro da Comunidade', 'comunidades/registro'),
	('Detalhes da Comunidade', 'comunidades/detalhes'),
	('Lista de Formulários', 'formularios'),
	('Registro de Formulário', 'formularios/registro'),
	('Detalhes do Formulário', 'formularios/detalhes'),
	('Dashboard', 'dashboard'),
	('Registro de Capítulos', 'capitulos/registro'),
	('Relatório', 'relatorios'),
	('Construtor de Formulários', 'formularios/construtor'),
	('Registro de Formulários', 'formularios/construtor/registro')
ON CONFLICT DO NOTHING;

/* User */
INSERT INTO "user" (email, name, register_date)
VALUES ('example@example.com', 'Administrator', current_date)
ON CONFLICT DO NOTHING;

/* Profile */
INSERT INTO profile (id, status, created_at, description, title, type, updated_at, created_by, modified_by)
VALUES (1, TRUE, current_date, 'Administrator ROLE', 'Administrator', 'ADMIN', current_date, (SELECT id FROM "user" WHERE name = 'Administrator'), (SELECT id FROM "user" WHERE name = 'Administrator'))
ON CONFLICT DO NOTHING;

/* Page Profile Permissions */
INSERT INTO profile_pages (can_create, can_delete, can_read, can_update, page_id, profile_id)
	(SELECT cast(TRUE AS BOOLEAN), cast(TRUE AS BOOLEAN), cast(TRUE AS BOOLEAN), cast(TRUE AS BOOLEAN), pages.id, profile.id
	 FROM public.profile, public.pages)
ON CONFLICT DO NOTHING;

/* Account */
INSERT INTO account (user_id, credentials_non_expired, enabled, account_non_expired, account_non_locked, password, login, profile_id)
VALUES((SELECT id FROM "user" WHERE name = 'Administrator'), TRUE, TRUE, TRUE, TRUE, '$2a$10$DHiwEO0otW0exjRhcsuhj.mJMUxZ2oAtQ/3SxVEXlETFd8WBn0Hqy', 'admin', (SELECT id FROM public.profile WHERE title = 'Administrator'))
ON CONFLICT DO NOTHING;

INSERT INTO states (id, uf_abbr, name)
VALUES (1, 'AC', 'Acre'), (2, 'AL', 'Alagoas'), (3, 'AM', 'Amazonas'), (4, 'AP', 'Amapá'), (5, 'BA', 'Bahia'),
(6, 'CE', 'Ceará'), (7, 'DF', 'Distrito Federal'), (8, 'ES', 'Espirito Santo'), (9, 'GO', 'Goiás'), (10, 'MA', 'Maranhão'),
(11, 'MG', 'Minas Gerais'), (12, 'MS', 'Mato Grosso do Sul'), (13, 'MT', 'Mato Grosso'), (14, 'PA', 'Pará'),
(15, 'PB', 'Paraíba'), (16, 'PE', 'Pernambuco'), (17, 'PI', 'Piauí'), (18, 'PR', 'Paraná'), (19, 'RJ', 'Rio de Janeiro'),
(20, 'RN', 'Rio Grande do Norte'), (21, 'RO', 'Rondônia'), (22, 'RR', 'Roraima'), (23, 'RS', 'Rio Grande do Sul'),
(24, 'SC', 'Santa Catarina'), (25, 'SE', 'Sergipe'), (26, 'SP', 'São Paulo'), (27, 'TO', 'Tocantins')
ON CONFLICT DO NOTHING;

INSERT INTO cities (id, name, state_id_fk)
VALUES (238, 'Manacapuru', 3), (239, 'Manaquirí', 3), (240, 'Manaus', 3), (241, 'Manicore', 3), (242, 'Maraa', 3),
(243, 'Massauari', 3), (244, 'Maues', 3), (245, 'Mocambo', 3)
ON CONFLICT DO NOTHING;