/* Create UUID Extension (assumes DB already created) */
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "citext";

/* Create SCHEMAS (Generated by Intellij) */
CREATE TABLE IF NOT EXISTS pages (
	id					BIGSERIAL                       NOT NULL	CONSTRAINT pages_pkey	PRIMARY KEY,
	title_url		VARCHAR(255)                    NOT NULL	CONSTRAINT title	UNIQUE,
	url_path		VARCHAR(255)                    NOT NULL,
	uuid				UUID DEFAULT uuid_generate_v4() NOT NULL
);


CREATE TABLE IF NOT EXISTS "user" (
	id            BIGSERIAL                       NOT NULL	CONSTRAINT user_pkey	PRIMARY KEY,
	email         VARCHAR(255)                    NOT NULL	CONSTRAINT email			UNIQUE,
	name          VARCHAR(255)                    NOT NULL,
	register_date TIMESTAMP                       NOT NULL,
	uuid          UUID DEFAULT uuid_generate_v4() NOT NULL	CONSTRAINT uuid				UNIQUE
);

CREATE TABLE IF NOT EXISTS profile (
	id          BIGSERIAL                       NOT NULL	CONSTRAINT profile_pkey			PRIMARY KEY,
	status      BOOLEAN,
	created_at  TIMESTAMP                       NOT NULL,
	description VARCHAR(255),
	title       VARCHAR(255)                    NOT NULL,
	type        CITEXT													NOT NULL,
	updated_at  TIMESTAMP                       NOT NULL,
	uuid        UUID DEFAULT uuid_generate_v4() NOT NULL,
	created_by  BIGINT                          NOT NULL	CONSTRAINT fk_user_created	REFERENCES "user",
	modified_by BIGINT                          NOT NULL	CONSTRAINT fk_user_modified	REFERENCES "user"
);

CREATE TABLE IF NOT EXISTS account (
	user_id              		BIGINT       NOT NULL	CONSTRAINT account_pkey	PRIMARY KEY	CONSTRAINT fk_user	REFERENCES "user",
	credentials_non_expired BOOLEAN      NOT NULL,
	enabled             		BOOLEAN      NOT NULL,
	account_non_expired     BOOLEAN      NOT NULL,
	account_non_locked      BOOLEAN      NOT NULL,
	password            		VARCHAR(255) NOT NULL,
	login               		VARCHAR(255) NOT NULL	CONSTRAINT login			UNIQUE,
	profile_id          		BIGINT       NOT NULL	CONSTRAINT fk_profile	REFERENCES profile
);

CREATE TABLE IF NOT EXISTS profile_pages(
	id         BIGSERIAL                       NOT NULL	CONSTRAINT profile_pages_pkey	PRIMARY KEY,
	can_create BOOLEAN,
	can_delete BOOLEAN,
	can_read   BOOLEAN,
	can_update BOOLEAN,
	uuid       UUID DEFAULT uuid_generate_v4() NOT NULL	CONSTRAINT uk_uuid				UNIQUE,
	page_id    BIGINT                          NOT NULL	CONSTRAINT fk_page		REFERENCES pages,
	profile_id BIGINT                          NOT NULL	CONSTRAINT fk_profile	REFERENCES profile,
	CONSTRAINT rule	UNIQUE (profile_id, page_id)
);

CREATE TABLE IF NOT EXISTS states (
	id      BIGINT       NOT NULL CONSTRAINT state_pkey	PRIMARY KEY,
	uf_abbr VARCHAR(255) NOT NULL CONSTRAINT uk_uf_abbr	UNIQUE,
	name    VARCHAR(255) NOT NULL CONSTRAINT uk_name		UNIQUE
);

CREATE TABLE IF NOT EXISTS cities (
	id          BIGINT       NOT NULL CONSTRAINT city_pkey	PRIMARY KEY,
	name        VARCHAR(255) NOT NULL,
	state_id_fk BIGINT       NOT NULL CONSTRAINT fk_state		REFERENCES states
);