/* Create UUID Extension (assumes DB already created) */
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

/* Create SCHEMAS (Generated by Intellij) */
CREATE TABLE IF NOT EXISTS pages (
	id				BIGSERIAL 		NOT NULL CONSTRAINT pages_pkey PRIMARY KEY,
	uuid 			UUID DEFAULT uuid_generate_v4() NOT NULL CONSTRAINT uk_tacamtwsc90cs3nua3ilsx1jj UNIQUE,
	title_url VARCHAR(255) NOT NULL CONSTRAINT uk_idglro7sy7291pbd1211ka3wj UNIQUE,
	url_path  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "user" (
	id          BIGSERIAL 		NOT NULL CONSTRAINT user_pkey PRIMARY KEY,
	email       VARCHAR(255) 	NOT NULL CONSTRAINT uk_ob8kqyqqgmefl0aco34akdtpe UNIQUE,
	uuid        UUID DEFAULT uuid_generate_v4() NOT NULL CONSTRAINT uk_d6m3sh7pcuyu7bl23r6uskljp UNIQUE,
	full_name   VARCHAR(255)  NOT NULL,
	dt_register TIMESTAMP			NOT NULL,
	type        VARCHAR(255)	NOT NULL
);

CREATE TABLE IF NOT EXISTS profile (
	id          BIGSERIAL                       NOT NULL	CONSTRAINT profile_pkey	PRIMARY KEY,
	status      BOOLEAN,
	created_at  TIMESTAMP                       NOT NULL,
	description VARCHAR(255),
	title       VARCHAR(255)                    NOT NULL	CONSTRAINT uk_o21xbfkn81ujdfbv6j4dgvv5h	UNIQUE,
	updated_at  TIMESTAMP                       NOT NULL,
	uuid        UUID DEFAULT uuid_generate_v4() NOT NULL	CONSTRAINT uk_qb094muc478nmtt02i5eajg6i	UNIQUE,
	created_by  BIGINT                          NOT NULL	CONSTRAINT fk9dwjioprpvom1gjc3vb3didbw	REFERENCES "user",
	modified_by BIGINT                          NOT NULL	CONSTRAINT fkru3elyid5iyi575vyt5e2v4bu	REFERENCES "user"
);

CREATE TABLE IF NOT EXISTS account (
	id                  BIGINT       NOT NULL	CONSTRAINT account_pkey	PRIMARY KEY	CONSTRAINT fk7y2xm0umcdojys1422d5walap REFERENCES "user",
	credentials_expired BOOLEAN      NOT NULL,
	enabled             BOOLEAN      NOT NULL,
	expired             BOOLEAN      NOT NULL,
	locked              BOOLEAN      NOT NULL,
	password            VARCHAR(255) NOT NULL,
	login               VARCHAR(255) NOT NULL	CONSTRAINT uk_5vxwyorsr92jce3ore6h93k6q	UNIQUE,
	profile_id          BIGINT       NOT NULL	CONSTRAINT fklelt1dhpyk7dqxdco3x3cd5ub REFERENCES profile
);

CREATE TABLE IF NOT EXISTS profile_pages (
	id         BIGSERIAL NOT NULL CONSTRAINT profile_pages_pkey PRIMARY KEY,
	can_create BOOLEAN,
	can_delete BOOLEAN,
	uuid       UUID DEFAULT uuid_generate_v4() NOT NULL CONSTRAINT uk_ek2lm9f3et7gre1k3ipnnbs0m UNIQUE,
	can_view   BOOLEAN,
	can_update BOOLEAN,
	page_id       BIGINT	NOT NULL	CONSTRAINT fk4h3hdiy81a4qjyhl94u35wbjt REFERENCES pages,
	profile_id    BIGINT 	NOT NULL	CONSTRAINT fk83dj0mj2va9fcwpgw1tta289f REFERENCES profile,
	CONSTRAINT ukjyvkiitug18b0ig8e7aoias82
	UNIQUE (profile_id, page_id)
);

CREATE TABLE IF NOT EXISTS state (
	id      BIGINT       NOT NULL CONSTRAINT state_pkey PRIMARY KEY,
	uf_abbr VARCHAR(255) NOT NULL CONSTRAINT uk_11llv031ayg9lcqp0k8jl3nd7 UNIQUE,
	name    VARCHAR(255) NOT NULL CONSTRAINT uk_2g0hi7w44i4sjkffh61pusaav UNIQUE
);

CREATE TABLE IF NOT EXISTS city (
	id          BIGINT       NOT NULL CONSTRAINT city_pkey PRIMARY KEY,
	name        VARCHAR(255) NOT NULL,
	state_id_fk BIGINT       NOT NULL CONSTRAINT fk5mkf8607s48qf9pi7fjgvhy76 REFERENCES state
);